In [1]:
import numpy as np

# Array

In [2]:
arr1 = np.array([1,2,3,4,5,6], dtype='float') 

In [3]:
arr1

array([1., 2., 3., 4., 5., 6.])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
print(arr1.dtype)

float64


#### Array of list

In [6]:
list_arr = [[1,2,3], [4,5], [6,7,8]]

In [7]:
list_arr1 = np.array(list_arr)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [8]:
list_arr1

array([list([1, 2, 3]), list([4, 5]), list([6, 7, 8])], dtype=object)

In [9]:
list_arr1.shape

(3,)

In [10]:
list_arr1.dtype    # Each element is of object type

dtype('O')

In [11]:
type(list_arr1)

numpy.ndarray

In [12]:
list_arr1.ndim

1

### Reshaping array

In [13]:
arr1 = np.array([1,2,3,4,5,6], dtype='float') 

In [14]:
arr1.reshape(3,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [15]:
arr2 = arr1.reshape(2,-1)     # When we don't know the number of columns, so we use -1 with assigning the desired no. of rows

                              # In short, rearrange array based on no. of rows

In [16]:
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
arr2.shape

(2, 3)

In [18]:
arr2.ndim

2

In [19]:
arr2.dtype

dtype('float64')

### Multiarray

In [20]:
mylist = list(range(1, 6))
mylist1 = list(range(11, 16))
mylist2 = list(range(21, 26))

In [21]:
mylist, mylist1, mylist2

([1, 2, 3, 4, 5], [11, 12, 13, 14, 15], [21, 22, 23, 24, 25])

In [22]:
multiarr = np.array([mylist,mylist1,mylist2])

In [23]:
multiarr

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [24]:
multiarr.shape

(3, 5)

In [25]:
multiarr.ndim    # 2 square brackets / we made array from list(mylist) of list(range) 

2

In [26]:
multiarr_15 = multiarr.reshape(1,15)
multiarr_15

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15, 21, 22, 23, 24, 25]])

In [27]:
multiarr_15.shape

(1, 15)

In [28]:
multiarr_15.ndim

2

In [29]:
multiarr_51 = multiarr.reshape(15,1)
multiarr_51

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [11],
       [12],
       [13],
       [14],
       [15],
       [21],
       [22],
       [23],
       [24],
       [25]])

In [30]:
(multiarr_51.shape), (multiarr_51.ndim) 

((15, 1), 2)

# arange()

In [31]:
a = np.arange(24)

In [32]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [33]:
a.shape

(24,)

In [34]:
a.ndim

1

In [35]:
b = a.reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [36]:
b.shape

(6, 4)

In [37]:
b.ndim

2

In [38]:
c = a.reshape(6,4,1)
c

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23]]])

In [39]:
c.shape

(6, 4, 1)

In [40]:
c.ndim

3

In [41]:
d = a.reshape(4,2,3)            #a.reshape((No.of Matrix), (No.of rows for each matrix), (No.of columns for each matrix))
d                               # Multiplication of these 3 values should be equal to total no. of elements in matrix

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

### Itemsize: 

In [42]:
x = np.array([1,2,3], dtype = np.int8)

In [43]:
x.itemsize     # 1 byte to store each element

1

In [44]:
x = np.array([1,2,3], dtype = np.int32)

In [45]:
x.itemsize    # 4 byte to store each element

4

In [46]:
x = np.array([1,2,3], dtype = np.float)

In [47]:
x.itemsize    # 8 byte to store each element

8

# Random

In [48]:
arr = np.random.randint(20,30,10)   # Generate 10 random numbers between 20 and 30
arr

array([29, 20, 29, 28, 27, 28, 23, 27, 28, 29])

In [49]:
## Video : 36 min

In [50]:
len(arr)

10

### Slicing and dicing

In [51]:
arr[2]

29

In [52]:
arr[-1]

29

In [53]:
arr[1:5]

array([20, 29, 28, 27])

In [54]:
arr[:5]

array([29, 20, 29, 28, 27])

In [55]:
arr[5:]

array([28, 23, 27, 28, 29])

### Broadcasting :
- Array slices are actually views on the the original array
- Rhat means, data isn't copied and any modifications to the viewwould be reflected back to the source array.

In [56]:
arr

array([29, 20, 29, 28, 27, 28, 23, 27, 28, 29])

In [57]:
# Just as assignment operator

arr[0:5] = 99

In [58]:
arr

array([99, 99, 99, 99, 99, 28, 23, 27, 28, 29])

#### Example:

In [59]:
new_arr = np.random.randint(10,20,10)

In [60]:
new_arr

array([17, 10, 15, 12, 12, 12, 16, 18, 12, 12])

In [61]:
new_arr_copy = new_arr.copy()

In [62]:
slice_new_arr = new_arr[0:5]

In [63]:
slice_new_arr

array([17, 10, 15, 12, 12])

In [64]:
slice_new_arr[0] = 100

In [65]:
slice_new_arr

array([100,  10,  15,  12,  12])

In [66]:
# The changes we made on sliced array are reflected on original array

# Reason: Numpy doesn't create a copy of sliced arrays, instead it creates view so if you make any chages, they'll reflect back on original array

# If you want to create copy or original array, use 'copy()' fuction and the do the operations on copied array

In [67]:
new_arr

array([100,  10,  15,  12,  12,  12,  16,  18,  12,  12])

In [68]:
new_arr_copy

array([17, 10, 15, 12, 12, 12, 16, 18, 12, 12])

### List and array

- The assignment operator for multile indices won't work for list but it works fine for array

In [69]:
list1 = list(range(1,10))

In [70]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [71]:
array = np.array(range(1,10))

In [72]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
list[0:5] = 99

TypeError: 'type' object does not support item assignment

In [74]:
array[0:5] = 99

In [75]:
array

array([99, 99, 99, 99, 99,  6,  7,  8,  9])

## Arithmetic operations

In [76]:
x = np.array([[4, 5], [7, 5]], dtype=np.float64)

In [77]:
y = np.array([[1, 3], [6, 9]], dtype=np.float64)

In [78]:
x

array([[4., 5.],
       [7., 5.]])

In [79]:
y

array([[1., 3.],
       [6., 9.]])

In [80]:
x.ndim, y.ndim

(2, 2)

#### 1. Addition

In [81]:
x + y

array([[ 5.,  8.],
       [13., 14.]])

In [82]:
np.add(x,y)

array([[ 5.,  8.],
       [13., 14.]])

#### Subtraction

In [83]:
x - y

array([[ 3.,  2.],
       [ 1., -4.]])

In [84]:
np.subtract(x,y)

array([[ 3.,  2.],
       [ 1., -4.]])

In [85]:
y - x

array([[-3., -2.],
       [-1.,  4.]])

In [86]:
np.subtract(y,x)

array([[-3., -2.],
       [-1.,  4.]])

#### 3. Multiplication

In [87]:
# simple multiplication and not a dot product

In [88]:
x * y

array([[ 4., 15.],
       [42., 45.]])

In [89]:
np.multiply(x,y)

array([[ 4., 15.],
       [42., 45.]])

#### 4. Dot product: 
- Matrix Multiplication: No. of column in first array should be equal to no. of rows in second array 

In [90]:
# x.y


# It will throw error

In [91]:
x.dot(y)

array([[34., 57.],
       [37., 66.]])

#### 5. Division

In [92]:
x / y

array([[4.        , 1.66666667],
       [1.16666667, 0.55555556]])

In [93]:
np.divide(x,y)

array([[4.        , 1.66666667],
       [1.16666667, 0.55555556]])

In [94]:
y / x

array([[0.25      , 0.6       ],
       [0.85714286, 1.8       ]])

In [95]:
np.divide(y,x)

array([[0.25      , 0.6       ],
       [0.85714286, 1.8       ]])

#### 6. Mode

In [96]:
np.divmod(x,y)

(array([[4., 1.],
        [1., 0.]]),
 array([[0., 2.],
        [1., 5.]]))

### Other operations for array elements:

#### 1. Sum

In [97]:
x

array([[4., 5.],
       [7., 5.]])

In [98]:
print(np.sum(x))   # Sum of all elements of array x

21.0


In [99]:
print(np.sum(x, axis = 0))    # Sum of all the elements in cloumn of array x 

[11. 10.]


In [100]:
print(np.sum(x, axis = 1))    # Sum of all the elements in rows of array x 

[ 9. 12.]


#### 2. Transpose

In [101]:
arr = np.arange(1,16)

In [102]:
arr = arr.reshape(3,5)

In [103]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [104]:
arr.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

#### 3. Maximun

In [105]:
x

array([[4., 5.],
       [7., 5.]])

In [106]:
y

array([[1., 3.],
       [6., 9.]])

In [107]:
np.maximum(x,y)

array([[4., 5.],
       [7., 9.]])

In [108]:
np.max(arr)

15

#### 4. Minimun

In [109]:
np.minimum(x,y)

array([[1., 3.],
       [6., 5.]])

In [110]:
np.min(arr)

1

#### 5. np.zeros_like(arr)

- Create a matrix of zeros having same structure as arr

In [111]:
a = np.array([[14, 15], [17, 15]], dtype=np.float64)

In [112]:
a

array([[14., 15.],
       [17., 15.]])

In [113]:
zero_a = np.zeros_like(a)

In [114]:
zero_a

array([[0., 0.],
       [0., 0.]])

In [115]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 5. np.ones_like(arr)

- Create a matrix of ones having same structure as arr

In [116]:
ones_a = np.ones_like(a)

In [117]:
ones_a

array([[1., 1.],
       [1., 1.]])

In [119]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])